## Importing libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
diabetes = pd.read_csv('diabetes.csv')

## Getting informations about the dataset

In [ ]:
diabetes.shape

(768, 9)

In [ ]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
diabetes.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [ ]:
diabetes.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [ ]:
diabetes['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

## Checking how the features affect the target variable

In [ ]:
diabetes.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

## Checking if there is any missing values in each column of the dataset

In [ ]:
diabetes.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

## The number of unique values in each column of the dataset

In [ ]:
diabetes.nunique()

Pregnancies                  17
Glucose                     136
BloodPressure                47
SkinThickness                51
Insulin                     186
BMI                         248
DiabetesPedigreeFunction    517
Age                          52
Outcome                       2
dtype: int64

## The independent variables and the dependent variable

In [ ]:
X = diabetes.iloc[:, :-1].values
y = diabetes.iloc[:, -1].values

In [ ]:
print(X.shape)
print(y.shape)

(768, 8)
(768,)


## Spliting the dataset into the training set and the test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=2)

## Feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Evaluating models

## 1- Logistic Regression model

In [ ]:
# 1- Training the model on the training set
# 2- Evaluating the model on the test set
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
classifier1 = LogisticRegression()
classifier1.fit(X_train, y_train)
y_pred1 = classifier1.predict(X_test)
cm1 = confusion_matrix(y_test, y_pred1)
score1 = accuracy_score(y_test, y_pred1)
print(cm1)
print(score1)

[[89 11]
 [26 28]]
0.7597402597402597


In [ ]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuarcies = cross_val_score(estimator=classifier1, X=X_train, y=y_train, cv=10)
print(f"The average accuracy: {accuarcies.mean():.2f}")
print(f"Standard Deviation: {accuarcies.std() * 100:.2f}%")

The average accuracy: 0.78
Standard Deviation: 4.58%


## 2- K-nearest neighbors (KNN) model

In [ ]:
# 1- Training the model on the training set
# 2- Evaluating the model on the test set
from sklearn.neighbors import KNeighborsClassifier
classifier2 = KNeighborsClassifier(n_neighbors=5, metric='minkowski')
classifier2.fit(X_train, y_train)
y_pred2 = classifier2.predict(X_test)
cm2 = confusion_matrix(y_test, y_pred2)
score2 = accuracy_score(y_test, y_pred2)
print(cm2)
print(score2)

[[87 13]
 [31 23]]
0.7142857142857143


In [ ]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuarcies = cross_val_score(estimator=classifier2, X=X_train, y=y_train, cv=10)
print(f"The average accuracy: {accuarcies.mean():.2f}")
print(f"Standard Deviation: {accuarcies.std() * 100:.2f}%")

The average accuracy: 0.73
Standard Deviation: 4.38%


## 3- Support vector machine (SVM) model

In [ ]:
# 1- Training the model on the training set
# 2- Evaluating the model on the test set
from sklearn.svm import SVC
classifier3 = SVC(kernel='linear')
classifier3.fit(X_train, y_train)
y_pred3 = classifier3.predict(X_test)
cm3 = confusion_matrix(y_test, y_pred3)
score3 = accuracy_score(y_test, y_pred3)
print(cm3)
print(score3)

[[91  9]
 [26 28]]
0.7727272727272727


In [ ]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuarcies = cross_val_score(estimator=classifier3, X=X_train, y=y_train, cv=10)
print(f"The average accuracy: {accuarcies.mean():.2f}")
print(f"Standard Deviation: {accuarcies.std() * 100:.2f}%")

The average accuracy: 0.77
Standard Deviation: 5.29%


## 4- Naive bayes model

In [ ]:
# 1- Training the model on the training set
# 2- Evaluating the model on the test set
from sklearn.naive_bayes import GaussianNB
classifier4 = GaussianNB()
classifier4.fit(X_train, y_train)
y_pred4 = classifier4.predict(X_test)
cm4 = confusion_matrix(y_test, y_pred4)
score4 = accuracy_score(y_test, y_pred4)
print(cm4)
print(score4)

[[88 12]
 [23 31]]
0.7727272727272727


In [ ]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuarcies = cross_val_score(estimator=classifier4, X=X_train, y=y_train, cv=10)
print(f"The average accuracy: {accuarcies.mean():.2f}")
print(f"Standard Deviation: {accuarcies.std() * 100:.2f}%")

The average accuracy: 0.75
Standard Deviation: 4.04%


## 5- Decision tree classification model

In [ ]:
# 1- Training the model on the training set
# 2- Evaluating the model on the test set
from sklearn.tree import DecisionTreeClassifier
classifier5 = DecisionTreeClassifier()
classifier5.fit(X_train, y_train)
y_pred5 = classifier5.predict(X_test)
cm5 = confusion_matrix(y_test, y_pred5)
score5 = accuracy_score(y_test, y_pred5)
print(cm5)
print(score5)

[[83 17]
 [29 25]]
0.7012987012987013


In [ ]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuarcies = cross_val_score(estimator=classifier5, X=X_train, y=y_train, cv=10)
print(f"The average accuracy: {accuarcies.mean():.2f}")
print(f"Standard Deviation: {accuarcies.std() * 100:.2f}%")

The average accuracy: 0.69
Standard Deviation: 5.39%


## 6- Random Forest Classification model

In [ ]:
# 1- Training the model on the training set
# 2- Evaluating the model on the test set
from sklearn.ensemble import RandomForestClassifier
classifier6 = RandomForestClassifier(n_estimators=10)
classifier6.fit(X_train, y_train)
y_pred6 = classifier6.predict(X_test)
cm6 = confusion_matrix(y_test, y_pred6)
score6 = accuracy_score(y_test, y_pred6)
print(cm6)
print(score6)

[[90 10]
 [34 20]]
0.7142857142857143


In [ ]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuarcies = cross_val_score(estimator=classifier6, X=X_train, y=y_train, cv=10)
print(f"The average accuracy: {accuarcies.mean():.2f}")
print(f"Standard Deviation: {accuarcies.std() * 100:.2f}%")

The average accuracy: 0.73
Standard Deviation: 4.12%


## Predicting if a person is diabetic or not using the SVM model

In [46]:
example = np.array([4,103,60,33,192,24,0.966,33]).reshape(1,-1)
y_pred = classifier3.predict(sc.transform(example))
print(y_pred)

[0]
